project:
  type: website

website:
  title: "The Brain Microbiome Atlas (BMA)"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer: |
    The BMA is brought to you by the [CINEMA Research Group](https://cwru-cinema.com/).
  reader-mode: true
  repo-url: https://github.com/sarah-grabinski/brain-microbiome-atlas
  repo-actions: [issue]
  open-graph: 
    image: /images/image.jpg
  description: |
    The Brain Microbiome Atlas (BMA) aggregates sequencing data for the brain microbiome and the brain-gut axis.
    
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    execute: 
      freeze: auto
      message: false
      warning: false
    code-links:
      repo: "https://github.com/sarah-grabinski/brain-microbiome-atlas/"

editor: visual

