---
title: "About"
---

The Brain Microbiome Atlas (BMA) aims to compile open-source data on the gut-brain axis and the possibility of a brain microbiome to help advance this exciting area of research. Open-source data has been aggregated on the following subjects.

# The Gut-Brain Axis

The gut microbiome consists of commensal or mutualistic bacteria which reside in the gastrointestinal tract and are involved in digestion, metabolism, regulation of the immune system, and protection against pathogens. The "gut-brain axis" is a term coined to describe the complex communication systems that appear to exist between the gut microbiota and the central nervous system and are associated with differences in physiology, behavior, and disease progression.

# Disease-Associated Microbes

The brain itself has traditionally been considered a sterile environment or a "dead end" for microbes. The brain's first line of defense, the blood-brain barrier, is thought to limit the intrusion of bacteria from the blood into the brain. Bacteria that evade the blood-brain barrier and proliferate in the brain can result in life-threatening inflammation. There is strong evidence linking neurodegenerative diseases with a compromised blood-brain barrier, and considerable work has been done to associate this with microbial infection of the brain.

# The Brain Microbiome

Studies investigating the relationship between neurodegeneration and microbiota have also produced evidence of microbes in the brains of healthy control cases, which suggests there may exist bacteria endogenous to the brain. Endogenous bacteria in the brain (a "brain microbiome") would consist of a set of microbes that persist (but not necessarily replicate) in the brain, the population of which is primarily quiescent and/or maintained by low level diffusion across the blood-brain barrier and active removal. If there is a "healthy" brain microbiome, one that exists in the absence of trauma and infection, it could represent a previously unknown mechanism by which the physiology of the brain is regulated.
